### ISSUE TITLE
Errata en una línea de 1.1

### ISSUE THREAD

**Issue by jaxlogan** [honecomp/honecomp.github.io#1]
¡Hola! He detectado una errata en el capítulo 1.1., «Historia»:

_se empezó **ha** hacer un esfuerzo por estandarizar los sistemas de tipo Unix_

por 

_se empezó **a** hacer un esfuerzo por estandarizar los sistemas de tipo Unix_.

**Comment by sysfatal** [comment]
Ouch!!!! 

Gracias, ya está corregida.
